# Koduppgift 5

### koduppgift 8

här importerar vi våra bibliotek och skapar en X som innehåller 3 columns och 1000 rows. Vi använder random för att få ut random värde i dom 

In [ ]:
import numpy as np
from sklearn.decomposition import PCA

X = np.random.rand(1000,3)
print(X[0:5])


[[0.13002309 0.25915087 0.72767703]
 [0.93124893 0.85001313 0.88625024]
 [0.93584324 0.65363133 0.22696599]
 [0.42110189 0.26652199 0.30579242]
 [0.76674879 0.10270996 0.55296285]]


Här använder vi PCA med n_components för att reducera ner det till 2 columns istället för 3

In [11]:
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
print(X2D[0:5])

[[-0.27753719  0.36269415]
 [ 0.66549892  0.13275264]
 [ 0.25910592 -0.39784533]
 [-0.27833349 -0.08283572]
 [-0.09682919  0.13170106]]


Här försöker vi återskapa våran 3 columns set men får false då den inte lyckas då skillnaden är förstår för att kunna återskapa.

In [12]:
X3d_inv = pca.inverse_transform(X2D)
print(np.allclose(X3d_inv,X))

False
